name:  megaglest-app  # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title:  MegaGlest  
summary: Forge Your Legacy in the Age of Megaliths" # 79 char long summary
description: |
  Will you shape history as a benevolent ruler, fostering prosperity and culture, or wield the forces of darkness to crush all who oppose you? 
  The fate of Glest lies in your hands. 	
  Strategize, conquer, and forge your legacy in this immersive real-time strategy adventure.


grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
   megaglest :
    command: bin/ megaglest-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
   megaglest :
    plugin: dump
    source: .
    organize:
       megaglest-bin: bin/
